# This workflow will build a Java project with Gradle and publish the docker artifact to dockerhub
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to DockerHub
      run: ./gradlew bootBuildImage
      env:
        dockerUsername: ${{ secrets.DOCKER_USERNAME }}
        dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        dockerUrl: ${{ secrets.DOCKER_URL }}
        dockerEmail: ${{ secrets.DOCKER_EMAIL }}
